# Generated by Django 2.1.5 on 2020-07-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
